version: '3.1'

services:
  app:
    build: .
    container_name: backend-empfo
    command: sh -c "npm run migrate"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # restart: always
    environment:
      POSTGRES_DB: dbempfo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080

volumes:
  db-data:  